package com.github.phillipkruger.user.model;

public enum RelationType {
        Spouse,
        Husband,
        Wife,
        Parent,
        Father,
        Mother,
        StepFather,
        StepMother,
        LegalGuardian,
        Child,
        Son,
        Daughter,
        StepSon,
        StepDaughter,
        Sibling,
        Brother,
        Sister,
        Stepfamily,
        Grandparent,
        Grandfather,
        Grandmother,
        Grandson,
        Granddaughter,
        Uncle,
        Aunt,
        Cousin,
        Nephew,
        Niece,
        FamilyInLaw,
        FatherInLaw,
        MotherInLaw,
        BrotherInLaw,
        SisterInLaw
}